language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
env:
  matrix:
    - BUILD_FLAGS=
    - BUILD_FLAGS=--no-default-features
    - BUILD_FLAGS=--no-default-features --features parsing
script:
  - cargo build $BUILD_FLAGS --verbose --all
  - cargo test $BUILD_FLAGS --verbose --all
